### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nnnlog**
AGPLv3

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Nice catch, but I will add this myself later. Thank you anyway.

**Comment by nnnlog** [comment]
@ishitatsuyuki Ok.

**Comment by ParkChanSol** [comment]
@ishitatsuyuki 
How do I excute Cenisys?
(If spam comment, I sorry)

**Comment by ParkChanSol** [comment]
@ishitatsuyuki 
How do I excute Cenisys

I know this is spam comment, but I want annouce Cenisys' Installation and existence to Korean

**Pull request closed without merging**
